# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yevheniiandrus/ArringoTest/simulator/CMakeLists.txt))

/Users/yevheniiandrus/ArringoTest/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.23.0/bin/cmake -H/Users/yevheniiandrus/ArringoTest -B/Users/yevheniiandrus/ArringoTest
